//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.04 at 06:16:44 PM YEKT 
//


package ru.hostco.reguser.types;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * \u041e\u0442\u0432\u0435\u0442 \u043d\u0430 \u0437\u0430\u043f\u0440\u043e\u0441 \u0441\u043f\u0438\u0441\u043a\u0430 \u0440\u043e\u043b\u0435\u0439
 * 
 * <p>Java class for GetRolesResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GetRolesResponseType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="SNILS" type="{http://www.hostco.ru/reguser/types}SNILSType" minOccurs="0"/&gt;
 *         &lt;choice&gt;
 *           &lt;element name="RoleList" type="{http://www.hostco.ru/reguser/types}RoleListType"/&gt;
 *           &lt;element name="Error" type="{http://www.hostco.ru/reguser/types}StandartResponseType"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetRolesResponseType", propOrder = {
    "snils",
    "roleList",
    "error"
})
public class GetRolesResponseType {

    @XmlElement(name = "SNILS")
    protected String snils;
    @XmlElement(name = "RoleList")
    protected RoleListType roleList;
    @XmlElement(name = "Error")
    protected StandartResponseType error;

    /**
     * Gets the value of the snils property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSNILS() {
        return snils;
    }

    /**
     * Sets the value of the snils property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSNILS(String value) {
        this.snils = value;
    }

    /**
     * Gets the value of the roleList property.
     * 
     * @return
     *     possible object is
     *     {@link RoleListType }
     *     
     */
    public RoleListType getRoleList() {
        return roleList;
    }

    /**
     * Sets the value of the roleList property.
     * 
     * @param value
     *     allowed object is
     *     {@link RoleListType }
     *     
     */
    public void setRoleList(RoleListType value) {
        this.roleList = value;
    }

    /**
     * Gets the value of the error property.
     * 
     * @return
     *     possible object is
     *     {@link StandartResponseType }
     *     
     */
    public StandartResponseType getError() {
        return error;
    }

    /**
     * Sets the value of the error property.
     * 
     * @param value
     *     allowed object is
     *     {@link StandartResponseType }
     *     
     */
    public void setError(StandartResponseType value) {
        this.error = value;
    }

}
