//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.04 at 06:16:44 PM YEKT 
//


package ru.hostco.reguser.types;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * \u0411\u0430\u0437\u043e\u0432\u044b\u0435 \u0441\u0432\u0435\u0434\u0435\u043d\u0438\u044f \u043e \u043b\u043e\u0433\u0438\u043d\u0435, \u0430\u0442\u0440\u0438\u0431\u0443\u0442\u044b, \u043e\u0431\u044f\u0437\u0430\u0442\u0435\u043b\u044c\u043d\u044b\u0435 \u043f\u0440\u0438 \u0440\u0435\u0433\u0438\u0441\u0442\u0440\u0430\u0446\u0438\u0438
 * 
 * <p>Java class for LoginStrictType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LoginStrictType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.hostco.ru/reguser/types}LoginType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="SNILS" type="{http://www.hostco.ru/reguser/types}SNILSType"/&gt;
 *         &lt;element name="Lastname" type="{http://www.hostco.ru/reguser/types}FIOType"/&gt;
 *         &lt;element name="Firstname" type="{http://www.hostco.ru/reguser/types}FIOType"/&gt;
 *         &lt;element name="Middlename" type="{http://www.hostco.ru/reguser/types}FIOType" minOccurs="0"/&gt;
 *         &lt;element name="BirthDate" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="Phone" type="{http://www.hostco.ru/reguser/types}PhoneType" minOccurs="0"/&gt;
 *         &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="gender" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="PolicyNumber" type="{http://www.hostco.ru/reguser/types}PolicyNumberType" minOccurs="0"/&gt;
 *         &lt;element name="birthPlace" type="{http://www.hostco.ru/reguser/types}BirthPlaceType" minOccurs="0"/&gt;
 *         &lt;element name="documents" type="{http://www.hostco.ru/reguser/types}DocumentsType" minOccurs="0"/&gt;
 *         &lt;element name="children" type="{http://www.hostco.ru/reguser/types}ChildrenType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LoginStrictType")
@XmlSeeAlso({
    RegUserRequestType.class
})
public class LoginStrictType
    extends LoginType
{


}
