//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.04 at 06:16:44 PM YEKT 
//


package ru.hostco.reguser.types;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ru.hostco.reguser.types package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _RegUserRequest_QNAME = new QName("http://www.hostco.ru/reguser/types", "regUserRequest");
    private final static QName _RegUserResponse_QNAME = new QName("http://www.hostco.ru/reguser/types", "regUserResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ru.hostco.reguser.types
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link StandartResponseType }
     * 
     */
    public StandartResponseType createStandartResponseType() {
        return new StandartResponseType();
    }

    /**
     * Create an instance of {@link StandartResponseType.ErrorList }
     * 
     */
    public StandartResponseType.ErrorList createStandartResponseTypeErrorList() {
        return new StandartResponseType.ErrorList();
    }

    /**
     * Create an instance of {@link RegUserRequestType }
     * 
     */
    public RegUserRequestType createRegUserRequestType() {
        return new RegUserRequestType();
    }

    /**
     * Create an instance of {@link RegUserResponseType }
     * 
     */
    public RegUserResponseType createRegUserResponseType() {
        return new RegUserResponseType();
    }

    /**
     * Create an instance of {@link EditUserRequestType }
     * 
     */
    public EditUserRequestType createEditUserRequestType() {
        return new EditUserRequestType();
    }

    /**
     * Create an instance of {@link EditUserResponseType }
     * 
     */
    public EditUserResponseType createEditUserResponseType() {
        return new EditUserResponseType();
    }

    /**
     * Create an instance of {@link ResetPasswordRequestType }
     * 
     */
    public ResetPasswordRequestType createResetPasswordRequestType() {
        return new ResetPasswordRequestType();
    }

    /**
     * Create an instance of {@link ResetPasswordResponseType }
     * 
     */
    public ResetPasswordResponseType createResetPasswordResponseType() {
        return new ResetPasswordResponseType();
    }

    /**
     * Create an instance of {@link GetUserRequestType }
     * 
     */
    public GetUserRequestType createGetUserRequestType() {
        return new GetUserRequestType();
    }

    /**
     * Create an instance of {@link GetUserResponseType }
     * 
     */
    public GetUserResponseType createGetUserResponseType() {
        return new GetUserResponseType();
    }

    /**
     * Create an instance of {@link GetRolesRequestType }
     * 
     */
    public GetRolesRequestType createGetRolesRequestType() {
        return new GetRolesRequestType();
    }

    /**
     * Create an instance of {@link GetRolesResponseType }
     * 
     */
    public GetRolesResponseType createGetRolesResponseType() {
        return new GetRolesResponseType();
    }

    /**
     * Create an instance of {@link SetRolesRequestType }
     * 
     */
    public SetRolesRequestType createSetRolesRequestType() {
        return new SetRolesRequestType();
    }

    /**
     * Create an instance of {@link SetRolesResponseType }
     * 
     */
    public SetRolesResponseType createSetRolesResponseType() {
        return new SetRolesResponseType();
    }

    /**
     * Create an instance of {@link AuthRequestType }
     * 
     */
    public AuthRequestType createAuthRequestType() {
        return new AuthRequestType();
    }

    /**
     * Create an instance of {@link AuthResponseType }
     * 
     */
    public AuthResponseType createAuthResponseType() {
        return new AuthResponseType();
    }

    /**
     * Create an instance of {@link ChangePasswordRequestType }
     * 
     */
    public ChangePasswordRequestType createChangePasswordRequestType() {
        return new ChangePasswordRequestType();
    }

    /**
     * Create an instance of {@link ChangePasswordResponseType }
     * 
     */
    public ChangePasswordResponseType createChangePasswordResponseType() {
        return new ChangePasswordResponseType();
    }

    /**
     * Create an instance of {@link GetAccessCodeRequestType }
     * 
     */
    public GetAccessCodeRequestType createGetAccessCodeRequestType() {
        return new GetAccessCodeRequestType();
    }

    /**
     * Create an instance of {@link GetAccessCodeResponseType }
     * 
     */
    public GetAccessCodeResponseType createGetAccessCodeResponseType() {
        return new GetAccessCodeResponseType();
    }

    /**
     * Create an instance of {@link CheckAccessCodeRequestType }
     * 
     */
    public CheckAccessCodeRequestType createCheckAccessCodeRequestType() {
        return new CheckAccessCodeRequestType();
    }

    /**
     * Create an instance of {@link ParentType }
     * 
     */
    public ParentType createParentType() {
        return new ParentType();
    }

    /**
     * Create an instance of {@link ChildrenType }
     * 
     */
    public ChildrenType createChildrenType() {
        return new ChildrenType();
    }

    /**
     * Create an instance of {@link DocumentsType }
     * 
     */
    public DocumentsType createDocumentsType() {
        return new DocumentsType();
    }

    /**
     * Create an instance of {@link WarningListType }
     * 
     */
    public WarningListType createWarningListType() {
        return new WarningListType();
    }

    /**
     * Create an instance of {@link WarningType }
     * 
     */
    public WarningType createWarningType() {
        return new WarningType();
    }

    /**
     * Create an instance of {@link StringID }
     * 
     */
    public StringID createStringID() {
        return new StringID();
    }

    /**
     * Create an instance of {@link IntID }
     * 
     */
    public IntID createIntID() {
        return new IntID();
    }

    /**
     * Create an instance of {@link DocIdType }
     * 
     */
    public DocIdType createDocIdType() {
        return new DocIdType();
    }

    /**
     * Create an instance of {@link RoleType }
     * 
     */
    public RoleType createRoleType() {
        return new RoleType();
    }

    /**
     * Create an instance of {@link RoleListType }
     * 
     */
    public RoleListType createRoleListType() {
        return new RoleListType();
    }

    /**
     * Create an instance of {@link UserIDType }
     * 
     */
    public UserIDType createUserIDType() {
        return new UserIDType();
    }

    /**
     * Create an instance of {@link LoginType }
     * 
     */
    public LoginType createLoginType() {
        return new LoginType();
    }

    /**
     * Create an instance of {@link PersonType }
     * 
     */
    public PersonType createPersonType() {
        return new PersonType();
    }

    /**
     * Create an instance of {@link ChildType }
     * 
     */
    public ChildType createChildType() {
        return new ChildType();
    }

    /**
     * Create an instance of {@link LoginStrictType }
     * 
     */
    public LoginStrictType createLoginStrictType() {
        return new LoginStrictType();
    }

    /**
     * Create an instance of {@link TmpPasswordResponseType }
     * 
     */
    public TmpPasswordResponseType createTmpPasswordResponseType() {
        return new TmpPasswordResponseType();
    }

    /**
     * Create an instance of {@link StandartResponseType.ErrorList.RecordError }
     * 
     */
    public StandartResponseType.ErrorList.RecordError createStandartResponseTypeErrorListRecordError() {
        return new StandartResponseType.ErrorList.RecordError();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RegUserRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.hostco.ru/reguser/types", name = "regUserRequest")
    public JAXBElement<RegUserRequestType> createRegUserRequest(RegUserRequestType value) {
        return new JAXBElement<RegUserRequestType>(_RegUserRequest_QNAME, RegUserRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RegUserResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.hostco.ru/reguser/types", name = "regUserResponse")
    public JAXBElement<RegUserResponseType> createRegUserResponse(RegUserResponseType value) {
        return new JAXBElement<RegUserResponseType>(_RegUserResponse_QNAME, RegUserResponseType.class, null, value);
    }

}
